title: Alberto Poncelas

baseurl:
pubs_path: /pubs
permalink: /:categories/:title
navigation:
    - title: About me
      link: /
    - title: CV
      link: /cv.html
    - title: Publications
      link: /publications.html
    - title: Presentations
      link: /presentations.html
    - title: Projects
      link: /projects.html


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false



