title: Alberto Poncelas

baseurl:
pubs_path: /pubs
permalink: /:categories/:title
navigation:
    - title: About me
      link: /
    - title: CV
      link: /cv.html
    - title: Publications
      link: /publications.html




# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false





# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


plugins: ['jekyll/scholar']

scholar:
  style: apa-no-doi-no-issue
  locale: en

  sort_by: none
  order: ascending

  repository: ./pubs
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }} {% if links.pdf %}<a href=\"{{ links.pdf }}\">PDF</a> {% endif %} "

  replace_strings: true
  join_strings:    true

  details_dir:    bibtex
  details_layout: bibtex.html
  details_link: BibTeX

  query: "@*"
